name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      - name: Commit pdf
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Upload pdf"
          add: "main.pdf"
          push: true
