name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      - name: Store pdf
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf
      - name: Commit pdf
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Dian Wang
          author_email: wangdian1007@outlook.com
          message: "Upload pdf"
          add: "main.pdf"
          push: true
